- include_tasks: nats-server.yaml
  when: nats_server_enabled == 'true'

- include_tasks: exporter.yaml
  when: nats_exporter_enabled == 'true'

- include_tasks: natscli.yaml
  when: natscli_enabled == 'true'
